pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/OnBoardingPart3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           
        }
        stage('Prepare test environment on DEV') {
            
        }
        stage('Prepare tests environment on ALPHA') {
            
        }
        stage('Prepare tests environment on PREPROD') {
            
        }
        stage('Deployment') {
            
        }
    }
}